### ISSUE TITLE
/tmp/jieba.cache prevents multiple users from running jieba

### ISSUE THREAD

**Issue by michelp** [fxsjy/jieba#26]
If two users run jieba at the same time, the first user will own /tmp/jieba.cache and the second user will get permission denied.  Can we have a way to specify this location in a configuration file so we don't have to hack the global temp file location for each user?

**Comment by kn45** [comment]
I got with this problem too.  This problem comes with two *USERS*, not two python *PROCESSES* by one same user.
When one user create /tmp/jieba.cache, the other one is not allowed to create this file nor overwrite it.
Quick fix is to `chmod 777 /tmp/jieba.cache`
One possible solution is set cache for each user separately for instance naming the cache file like /tmp/jieba.cache.${USER_NAME}

**Comment by longbowking** [comment]
looks like the problem is still there ...

**Comment by wizardk** [comment]
It would be better to move this file to shared memory.
